/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2compiladores;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 57304
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        MTable.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        GraSinV_Area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Prim_Area = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Sgte_Area = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        MTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        SegTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        EscogerG_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ProdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GraSinV_Area.setColumns(20);
        GraSinV_Area.setRows(5);
        jScrollPane1.setViewportView(GraSinV_Area);

        Prim_Area.setColumns(20);
        Prim_Area.setRows(5);
        jScrollPane2.setViewportView(Prim_Area);

        Sgte_Area.setColumns(20);
        Sgte_Area.setRows(5);
        jScrollPane3.setViewportView(Sgte_Area);

        MTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(MTable);

        SegTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(SegTable);

        jLabel1.setText("Gramatica:");

        EscogerG_Button.setText("Adjuntar gramatica");
        EscogerG_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscogerG_ButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Cadena a verificar:");

        ProdLabel.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EscogerG_Button))
                            .addComponent(jLabel2)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ProdLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(EscogerG_Button))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProdLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscogerG_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscogerG_ButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = chooser.getSelectedFile();
        try {
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);

            //lectura de producciones
            String line;
            ArrayList<String> producciones = new ArrayList();
             while ((line = br.readLine()) != null) {
                     System.out.println(line);
                     producciones.add(line);
             }
             
             for (String produccion : producciones) {
                if (produccion.length() != 3) {
                    produccion.replace("&", "");
                }
            }
             
             Gramatica gramatica = new Gramatica(producciones);
   
             DefaultTableModel MTableModel = (DefaultTableModel) MTable.getModel();
             MTableModel.setRowCount(0);
             MTableModel.setColumnCount(0); 
             Prim_Area.setText("");
             Sgte_Area.setText("");
             String [][] M = gramatica.M;
             ArrayList<String> elementos = new ArrayList();
             
             String prod_original =  "<html>Producciones originales:";
             for (int i = 0; i < gramatica.producciones.size(); i++) {
                prod_original+="<br> &emsp; &emsp; &emsp;"+gramatica.producciones.get(i);
            }
             prod_original+="</html>";
             ProdLabel.setText(prod_original);
             
             GraSinV_Area.append("-------GRAMATICA SIN VICIOS--------\n");
             for (String produccion: gramatica.ProdSinV) {
                GraSinV_Area.append(produccion+"\n");
            }
            
            Prim_Area.append("-------PRIMEROS--------\n");
            for (Map.Entry<String, ArrayList> entry : gramatica.primeros.entrySet()) {
            Prim_Area.append(entry.getKey()+"="+entry.getValue().toString()+"\n");
            }
            
            Sgte_Area.append("-------SIGUIENTES--------\n");
            for (Map.Entry<String, ArrayList> entry : gramatica.siguientes.entrySet()) {
            Sgte_Area.append(entry.getKey()+"="+entry.getValue().toString()+"\n");
            }
             
            
            for (int i = 0; i < gramatica.Terminales.size()+1; i++) {
                MTableModel.addColumn(M[0][i]);
            }

             for (int i = 1; i < gramatica.NoTerminales.size()+1; i++) {
                 elementos = new ArrayList();
                 for (int j = 0; j < gramatica.Terminales.size()+1; j++) {
                     elementos.add(M[i][j]);
                 }
                 MTableModel.addRow(elementos.toArray());
            }
             

        }catch (FileNotFoundException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EscogerG_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EscogerG_Button;
    private javax.swing.JTextArea GraSinV_Area;
    private javax.swing.JTable MTable;
    private javax.swing.JTextArea Prim_Area;
    private javax.swing.JLabel ProdLabel;
    private javax.swing.JTable SegTable;
    private javax.swing.JTextArea Sgte_Area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
